/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package KeyboardSync;

import java.io.File;
import java.io.IOException;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;

public class App {
    static final String PATH = System.getProperty("user.dir");
    static final String MEDIA = "\\static\\";

    public static void main(String[] args) {
        EdgeDetection ed = new EdgeDetection();
        Vision cv = new Vision();
        
        BufferedImage img = null;

        // grab image from source
        try {
            img = ImageIO.read(new File(PATH + MEDIA + "img.png"));

        } catch (IOException e) {
            System.out.println("An error occured whilst procuring image. :(");
        }

        // edge detection with sobel
        BufferedImage sobImg = ed.sobel(img);

        // try to houghspace?
        BufferedImage houImg = cv.houghLines(sobImg, 1.0, true);
        Graphics2D canvas = houImg.createGraphics();
        
        canvas.draw3DRect(0, 10, 50, 20, true);

        File ouptut = new File(PATH + MEDIA + "output.png");
        try{
            ImageIO.write(houImg, "png", ouptut);

        } catch (IOException e){
            System.out.println("An error occured whilst writing image. :(");
        }
    }
}
